#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Section {
    Startup,
    Logging,
    Download,
    Directory,
    Http,
    Https,
    Warc,
    Ftp,
    Ftps,
    Recursive,
    AcceptReject,
}

impl Section {
    pub fn title(self) -> &'static str {
        match self {
            Section::Startup => "Startup",
            Section::Logging => "Logging and input",
            Section::Download => "Download",
            Section::Directory => "Directories",
            Section::Http => "HTTP",
            Section::Https => "HTTPS (SSL/TLS)",
            Section::Warc => "WARC",
            Section::Ftp => "FTP",
            Section::Ftps => "FTPS",
            Section::Recursive => "Recursive retrieval",
            Section::AcceptReject => "Recursive accept/reject",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct OptMeta {
    pub long: &'static str,
    pub short: Option<char>,
    pub takes_value: bool,
    pub section: Section,
    pub help: &'static str,
}

pub static OPTIONS: &[OptMeta] = &[
    OptMeta {
        long: "version",
        short: Some('V'),
        takes_value: false,
        section: Section::Startup,
        help: "display the version of fetchling and exit",
    },
    OptMeta {
        long: "help",
        short: Some('h'),
        takes_value: false,
        section: Section::Startup,
        help: "print this help",
    },
    OptMeta {
        long: "background",
        short: Some('b'),
        takes_value: false,
        section: Section::Startup,
        help: "go to background after startup",
    },
    OptMeta {
        long: "execute",
        short: Some('e'),
        takes_value: true,
        section: Section::Startup,
        help: "execute a wgetrc-style command",
    },
    OptMeta {
        long: "output-file",
        short: Some('o'),
        takes_value: true,
        section: Section::Logging,
        help: "log messages to FILE",
    },
    OptMeta {
        long: "append-output",
        short: Some('a'),
        takes_value: true,
        section: Section::Logging,
        help: "append messages to FILE",
    },
    OptMeta {
        long: "debug",
        short: Some('d'),
        takes_value: false,
        section: Section::Logging,
        help: "print lots of debugging information",
    },
    OptMeta {
        long: "quiet",
        short: Some('q'),
        takes_value: false,
        section: Section::Logging,
        help: "quiet (no output)",
    },
    OptMeta {
        long: "verbose",
        short: Some('v'),
        takes_value: false,
        section: Section::Logging,
        help: "be verbose (default)",
    },
    OptMeta {
        long: "no-verbose",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "turn off verboseness, without being quiet",
    },
    OptMeta {
        long: "report-speed",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "report bandwidth in bits/s (type=bits)",
    },
    OptMeta {
        long: "input-file",
        short: Some('i'),
        takes_value: true,
        section: Section::Logging,
        help: "download URLs found in local or external FILE",
    },
    OptMeta {
        long: "input-metalink",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "download files covered in local Metalink FILE",
    },
    OptMeta {
        long: "keep-badhash",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "keep Metalink downloads with checksum mismatch",
    },
    OptMeta {
        long: "metalink-over-http",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "use Metalink metadata from HTTP headers",
    },
    OptMeta {
        long: "metalink-index",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "Metalink application/metalink4+xml metaurl ordinal",
    },
    OptMeta {
        long: "preferred-location",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "preferred location for Metalink resources",
    },
    OptMeta {
        long: "force-html",
        short: Some('F'),
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as HTML",
    },
    OptMeta {
        long: "force-css",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as CSS",
    },
    OptMeta {
        long: "force-metalink",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as a Metalink document",
    },
    OptMeta {
        long: "force-rss",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as RSS",
    },
    OptMeta {
        long: "force-atom",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as Atom",
    },
    OptMeta {
        long: "force-sitemap",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "treat input file as a sitemap",
    },
    OptMeta {
        long: "base",
        short: Some('B'),
        takes_value: true,
        section: Section::Logging,
        help: "resolves relative links using URL as base",
    },
    OptMeta {
        long: "config",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "specify config file to use",
    },
    OptMeta {
        long: "no-config",
        short: None,
        takes_value: false,
        section: Section::Logging,
        help: "do not read any config file",
    },
    OptMeta {
        long: "rejected-log",
        short: None,
        takes_value: true,
        section: Section::Logging,
        help: "log reasons for URL rejection to FILE",
    },
    OptMeta {
        long: "bind-address",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "bind to ADDRESS (hostname or IP) on local host",
    },
    OptMeta {
        long: "bind-dns-address",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "bind DNS requests to ADDRESS (libcares)",
    },
    OptMeta {
        long: "dns-servers",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "override DNS servers (libcares)",
    },
    OptMeta {
        long: "tries",
        short: Some('t'),
        takes_value: true,
        section: Section::Download,
        help: "set number of retries to NUMBER (0 = unlimited)",
    },
    OptMeta {
        long: "output-document",
        short: Some('O'),
        takes_value: true,
        section: Section::Download,
        help: "write documents to FILE",
    },
    OptMeta {
        long: "no-clobber",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "skip downloads that would overwrite existing files (also -nc)",
    },
    OptMeta {
        long: "clobber",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "overwrite existing files (default; clears --unique-names)",
    },
    OptMeta {
        long: "unique-names",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "on collision, write to file.1, file.2, … instead of overwriting (fetchling)",
    },
    OptMeta {
        long: "backups",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "rotate numbered backups before overwriting",
    },
    OptMeta {
        long: "continue",
        short: Some('c'),
        takes_value: false,
        section: Section::Download,
        help: "resume getting a partially-downloaded file",
    },
    OptMeta {
        long: "start-pos",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "start downloading at zero-based OFFSET",
    },
    OptMeta {
        long: "progress",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "progress indicator type (bar/dot)",
    },
    OptMeta {
        long: "show-progress",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "display the progress bar in any verbosity",
    },
    OptMeta {
        long: "force-progress",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "alias for --show-progress",
    },
    OptMeta {
        long: "timestamping",
        short: Some('N'),
        takes_value: false,
        section: Section::Download,
        help: "don't re-retrieve files unless newer than local",
    },
    OptMeta {
        long: "no-if-modified-since",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "don't send If-Modified-Since in -N mode",
    },
    OptMeta {
        long: "no-use-server-timestamps",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "don't set local file timestamp from server",
    },
    OptMeta {
        long: "use-server-timestamps",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "set local file timestamp from server (default)",
    },
    OptMeta {
        long: "server-response",
        short: Some('S'),
        takes_value: false,
        section: Section::Download,
        help: "print server response",
    },
    OptMeta {
        long: "spider",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "don't download anything",
    },
    OptMeta {
        long: "timeout",
        short: Some('T'),
        takes_value: true,
        section: Section::Download,
        help: "set all timeout values to SECONDS",
    },
    OptMeta {
        long: "dns-timeout",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set DNS lookup timeout to SECONDS",
    },
    OptMeta {
        long: "connect-timeout",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set connect timeout to SECONDS",
    },
    OptMeta {
        long: "read-timeout",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set read timeout to SECONDS",
    },
    OptMeta {
        long: "limit-rate",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "limit download rate to RATE",
    },
    OptMeta {
        long: "wait",
        short: Some('w'),
        takes_value: true,
        section: Section::Download,
        help: "wait SECONDS between retrievals",
    },
    OptMeta {
        long: "waitretry",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "wait 1..SECONDS between retries of a retrieval",
    },
    OptMeta {
        long: "random-wait",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "wait from 0.5*WAIT...1.5*WAIT secs between retrievals",
    },
    OptMeta {
        long: "no-proxy",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "explicitly turn off proxy",
    },
    OptMeta {
        long: "http-proxy",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set HTTP proxy URL",
    },
    OptMeta {
        long: "https-proxy",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set HTTPS proxy URL",
    },
    OptMeta {
        long: "proxy",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set HTTP and HTTPS proxy URL",
    },
    OptMeta {
        long: "quota",
        short: Some('Q'),
        takes_value: true,
        section: Section::Download,
        help: "set retrieval quota to NUMBER",
    },
    OptMeta {
        long: "no-dns-cache",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "disable caching DNS lookups",
    },
    OptMeta {
        long: "restrict-file-names",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "restrict characters in local file names",
    },
    OptMeta {
        long: "inet4-only",
        short: Some('4'),
        takes_value: false,
        section: Section::Download,
        help: "connect only to IPv4 addresses",
    },
    OptMeta {
        long: "inet6-only",
        short: Some('6'),
        takes_value: false,
        section: Section::Download,
        help: "connect only to IPv6 addresses",
    },
    OptMeta {
        long: "prefer-family",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "prefer address family (IPv4/IPv6/none)",
    },
    OptMeta {
        long: "retry-connrefused",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "retry even if connection is refused",
    },
    OptMeta {
        long: "user",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set both ftp and http user to USER",
    },
    OptMeta {
        long: "password",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "set both ftp and http password to PASS",
    },
    OptMeta {
        long: "ask-password",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "prompt for passwords",
    },
    OptMeta {
        long: "use-askpass",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "prompt for credentials with COMMAND",
    },
    OptMeta {
        long: "no-iri",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "disable IRI support",
    },
    OptMeta {
        long: "local-encoding",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "use ENC as the local encoding for IRIs",
    },
    OptMeta {
        long: "remote-encoding",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "use ENC as the default remote encoding",
    },
    OptMeta {
        long: "unlink",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "remove file before clobber",
    },
    OptMeta {
        long: "xattr",
        short: None,
        takes_value: false,
        section: Section::Download,
        help: "turn on storage of metadata in extended attributes",
    },
    OptMeta {
        long: "no-directories",
        short: None,
        takes_value: false,
        section: Section::Directory,
        help: "don't create directories",
    },
    OptMeta {
        long: "force-directories",
        short: Some('x'),
        takes_value: false,
        section: Section::Directory,
        help: "force creation of directories",
    },
    OptMeta {
        long: "no-host-directories",
        short: None,
        takes_value: false,
        section: Section::Directory,
        help: "don't create host directories",
    },
    OptMeta {
        long: "protocol-directories",
        short: None,
        takes_value: false,
        section: Section::Directory,
        help: "use protocol name in local directory names",
    },
    OptMeta {
        long: "cut-dirs",
        short: None,
        takes_value: true,
        section: Section::Directory,
        help: "ignore NUMBER directory components",
    },
    OptMeta {
        long: "directory-prefix",
        short: Some('P'),
        takes_value: true,
        section: Section::Directory,
        help: "save files to PREFIX/...",
    },
    OptMeta {
        long: "default-page",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "default page name (default: index.html)",
    },
    OptMeta {
        long: "adjust-extension",
        short: Some('E'),
        takes_value: false,
        section: Section::Http,
        help: "save HTML/CSS documents with proper extensions",
    },
    OptMeta {
        long: "http-user",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "set http user to USER",
    },
    OptMeta {
        long: "http-password",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "set http password to PASS",
    },
    OptMeta {
        long: "no-http-keep-alive",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "disable HTTP keep-alive",
    },
    OptMeta {
        long: "max-threads",
        short: None,
        takes_value: true,
        section: Section::Download,
        help: "max concurrent downloads (1..=32, default 1)",
    },
    OptMeta {
        long: "no-cache",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "disallow server-cached data",
    },
    OptMeta {
        long: "no-cookies",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "don't use cookies",
    },
    OptMeta {
        long: "load-cookies",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "load cookies from FILE before session",
    },
    OptMeta {
        long: "save-cookies",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "save cookies to FILE after session",
    },
    OptMeta {
        long: "keep-session-cookies",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "load and save session (non-permanent) cookies",
    },
    OptMeta {
        long: "ignore-length",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "ignore Content-Length header",
    },
    OptMeta {
        long: "header",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "insert STRING among the headers",
    },
    OptMeta {
        long: "compression",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "choose compression (auto/gzip/none)",
    },
    OptMeta {
        long: "max-redirect",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "maximum redirections to follow",
    },
    OptMeta {
        long: "proxy-user",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "set proxy user to USER",
    },
    OptMeta {
        long: "proxy-password",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "set proxy password to PASS",
    },
    OptMeta {
        long: "referer",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "include Referer: URL header",
    },
    OptMeta {
        long: "save-headers",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "save the HTTP headers to file",
    },
    OptMeta {
        long: "user-agent",
        short: Some('U'),
        takes_value: true,
        section: Section::Http,
        help: "identify as AGENT instead of fetchling/VERSION",
    },
    OptMeta {
        long: "post-data",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "use POST method and send STRING as data",
    },
    OptMeta {
        long: "post-file",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "use POST and send contents of FILE",
    },
    OptMeta {
        long: "method",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "use method HTTP-Method in the request",
    },
    OptMeta {
        long: "body-data",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "send STRING as data (requires --method)",
    },
    OptMeta {
        long: "body-file",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "send contents of FILE as data (requires --method)",
    },
    OptMeta {
        long: "content-disposition",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "honor Content-Disposition filename",
    },
    OptMeta {
        long: "content-on-error",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "output the received content on server errors",
    },
    OptMeta {
        long: "trust-server-names",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "use the last redirect's filename",
    },
    OptMeta {
        long: "auth-no-challenge",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "send Basic HTTP authentication without first waiting for the challenge",
    },
    OptMeta {
        long: "retry-on-host-error",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "consider host errors as non-fatal",
    },
    OptMeta {
        long: "retry-on-http-error",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "retry on given HTTP status codes",
    },
    OptMeta {
        long: "no-netrc",
        short: None,
        takes_value: false,
        section: Section::Http,
        help: "don't try to obtain credentials from .netrc",
    },
    OptMeta {
        long: "netrc-file",
        short: None,
        takes_value: true,
        section: Section::Http,
        help: "specify netrc file to use (default: ~/.netrc)",
    },
    OptMeta {
        long: "secure-protocol",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "TLS protocol to use (auto/TLSv1_2/TLSv1_3)",
    },
    OptMeta {
        long: "https-only",
        short: None,
        takes_value: false,
        section: Section::Https,
        help: "only follow secure HTTPS links",
    },
    OptMeta {
        long: "ciphers",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "accepted for compatibility; ignored (rustls has no OpenSSL/GnuTLS cipher language)",
    },
    OptMeta {
        long: "no-check-certificate",
        short: None,
        takes_value: false,
        section: Section::Https,
        help: "don't validate the server's certificate",
    },
    OptMeta {
        long: "certificate",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "client certificate file",
    },
    OptMeta {
        long: "certificate-type",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "client certificate type (PEM/DER/ASN1)",
    },
    OptMeta {
        long: "private-key",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "private key file",
    },
    OptMeta {
        long: "private-key-type",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "private key type (PEM/DER/ASN1)",
    },
    OptMeta {
        long: "ca-certificate",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "file with CA certificates",
    },
    OptMeta {
        long: "ca-directory",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "directory with CA certificates",
    },
    OptMeta {
        long: "crl-file",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "file with CRL certificates",
    },
    OptMeta {
        long: "pinnedpubkey",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "pin public key (SHA256) of certificate",
    },
    OptMeta {
        long: "random-file",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "ignored (compatibility; modern TLS does not use file seeding)",
    },
    OptMeta {
        long: "egd-file",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "ignored (compatibility; modern TLS does not use EGD seeding)",
    },
    OptMeta {
        long: "no-hsts",
        short: None,
        takes_value: false,
        section: Section::Https,
        help: "disable HSTS",
    },
    OptMeta {
        long: "hsts-file",
        short: None,
        takes_value: true,
        section: Section::Https,
        help: "path of HSTS database",
    },
    OptMeta {
        long: "warc-file",
        short: None,
        takes_value: true,
        section: Section::Warc,
        help: "save request/response data to a .warc.gz file",
    },
    OptMeta {
        long: "warc-header",
        short: None,
        takes_value: true,
        section: Section::Warc,
        help: "insert STRING into the warcinfo record",
    },
    OptMeta {
        long: "warc-max-size",
        short: None,
        takes_value: true,
        section: Section::Warc,
        help: "set maximum size of WARC files to NUMBER",
    },
    OptMeta {
        long: "warc-cdx",
        short: None,
        takes_value: false,
        section: Section::Warc,
        help: "write CDX index files",
    },
    OptMeta {
        long: "warc-dedup",
        short: None,
        takes_value: true,
        section: Section::Warc,
        help: "do not store records listed in CDX FILE",
    },
    OptMeta {
        long: "no-warc-compression",
        short: None,
        takes_value: false,
        section: Section::Warc,
        help: "do not compress WARC files",
    },
    OptMeta {
        long: "no-warc-digests",
        short: None,
        takes_value: false,
        section: Section::Warc,
        help: "do not calculate SHA1 digests",
    },
    OptMeta {
        long: "no-warc-keep-log",
        short: None,
        takes_value: false,
        section: Section::Warc,
        help: "do not store the log file in a WARC record",
    },
    OptMeta {
        long: "warc-tempdir",
        short: None,
        takes_value: true,
        section: Section::Warc,
        help: "location for temporary files",
    },
    OptMeta {
        long: "ftp-user",
        short: None,
        takes_value: true,
        section: Section::Ftp,
        help: "set ftp user to USER",
    },
    OptMeta {
        long: "ftp-password",
        short: None,
        takes_value: true,
        section: Section::Ftp,
        help: "set ftp password to PASS",
    },
    OptMeta {
        long: "no-remove-listing",
        short: None,
        takes_value: false,
        section: Section::Ftp,
        help: "don't remove .listing files",
    },
    OptMeta {
        long: "no-glob",
        short: None,
        takes_value: false,
        section: Section::Ftp,
        help: "turn off file name globbing",
    },
    OptMeta {
        long: "no-passive-ftp",
        short: None,
        takes_value: false,
        section: Section::Ftp,
        help: "disable the PASV/EPSV command",
    },
    OptMeta {
        long: "preserve-permissions",
        short: None,
        takes_value: false,
        section: Section::Ftp,
        help: "preserve remote file permissions",
    },
    OptMeta {
        long: "retr-symlinks",
        short: None,
        takes_value: false,
        section: Section::Ftp,
        help: "when recursing, get linked-to files (not dir)",
    },
    OptMeta {
        long: "ftps-implicit",
        short: None,
        takes_value: false,
        section: Section::Ftps,
        help: "use implicit FTPS (default port 990)",
    },
    OptMeta {
        long: "no-ftps-resume-ssl",
        short: None,
        takes_value: false,
        section: Section::Ftps,
        help: "don't resume SSL/TLS session in data connection",
    },
    OptMeta {
        long: "ftps-clear-data-connection",
        short: None,
        takes_value: false,
        section: Section::Ftps,
        help: "send PROT C to clear data channel",
    },
    OptMeta {
        long: "ftps-fallback-to-ftp",
        short: None,
        takes_value: false,
        section: Section::Ftps,
        help: "fall back to FTP if FTPS is not supported",
    },
    OptMeta {
        long: "recursive",
        short: Some('r'),
        takes_value: false,
        section: Section::Recursive,
        help: "specify recursive download",
    },
    OptMeta {
        long: "level",
        short: Some('l'),
        takes_value: true,
        section: Section::Recursive,
        help: "maximum recursion depth (0 or inf = infinite)",
    },
    OptMeta {
        long: "delete-after",
        short: None,
        takes_value: false,
        section: Section::Recursive,
        help: "delete files locally after downloading them",
    },
    OptMeta {
        long: "convert-links",
        short: Some('k'),
        takes_value: false,
        section: Section::Recursive,
        help: "make links in downloaded HTML or CSS point to local files",
    },
    OptMeta {
        long: "convert-file-only",
        short: None,
        takes_value: false,
        section: Section::Recursive,
        help: "convert the file part of the URLs only",
    },
    OptMeta {
        long: "backup-converted",
        short: Some('K'),
        takes_value: false,
        section: Section::Recursive,
        help: "before converting file X, back up as X.orig",
    },
    OptMeta {
        long: "mirror",
        short: Some('m'),
        takes_value: false,
        section: Section::Recursive,
        help: "shortcut for -N -r -l inf --no-remove-listing",
    },
    OptMeta {
        long: "page-requisites",
        short: Some('p'),
        takes_value: false,
        section: Section::Recursive,
        help: "get all images, etc. needed to display HTML page",
    },
    OptMeta {
        long: "strict-comments",
        short: None,
        takes_value: false,
        section: Section::Recursive,
        help: "turn on strict parsing of HTML comments",
    },
    OptMeta {
        long: "accept",
        short: Some('A'),
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of accepted extensions",
    },
    OptMeta {
        long: "reject",
        short: Some('R'),
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of rejected extensions",
    },
    OptMeta {
        long: "filter-mime-type",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of accepted MIME types",
    },
    OptMeta {
        long: "cut-url-get-vars",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "remove listed query variables from request URLs (empty = all)",
    },
    OptMeta {
        long: "cut-file-get-vars",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "remove listed query variables from local filenames (empty = all)",
    },
    OptMeta {
        long: "accept-regex",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "regex of accepted URLs",
    },
    OptMeta {
        long: "reject-regex",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "regex of rejected URLs",
    },
    OptMeta {
        long: "regex-type",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "regex type (posix|pcre)",
    },
    OptMeta {
        long: "domains",
        short: Some('D'),
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of accepted domains",
    },
    OptMeta {
        long: "exclude-domains",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of excluded domains",
    },
    OptMeta {
        long: "follow-ftp",
        short: None,
        takes_value: false,
        section: Section::AcceptReject,
        help: "follow FTP links from HTML documents",
    },
    OptMeta {
        long: "follow-sitemaps",
        short: None,
        takes_value: false,
        section: Section::AcceptReject,
        help: "parse and follow sitemaps from robots.txt",
    },
    OptMeta {
        long: "follow-tags",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of followed HTML tags",
    },
    OptMeta {
        long: "ignore-tags",
        short: None,
        takes_value: true,
        section: Section::AcceptReject,
        help: "comma-separated list of ignored HTML tags",
    },
    OptMeta {
        long: "ignore-case",
        short: None,
        takes_value: false,
        section: Section::AcceptReject,
        help: "ignore case when matching files/directories",
    },
    OptMeta {
        long: "span-hosts",
        short: Some('H'),
        takes_value: false,
        section: Section::AcceptReject,
        help: "go to foreign hosts when recursive",
    },
    OptMeta {
        long: "relative",
        short: Some('L'),
        takes_value: false,
        section: Section::AcceptReject,
        help: "follow relative links only",
    },
    OptMeta {
        long: "include-directories",
        short: Some('I'),
        takes_value: true,
        section: Section::AcceptReject,
        help: "list of allowed directories",
    },
    OptMeta {
        long: "exclude-directories",
        short: Some('X'),
        takes_value: true,
        section: Section::AcceptReject,
        help: "list of excluded directories",
    },
    OptMeta {
        long: "no-parent",
        short: None,
        takes_value: false,
        section: Section::AcceptReject,
        help: "don't ascend to the parent directory",
    },
];
