[workspace]
resolver = "2"
members = [
    "crates/fetchling",
    "crates/fetchling-cli",
    "crates/fetchling-core",
    "crates/fetchling-net",
    "crates/fetchling-http",
    "crates/fetchling-ftp",
    "crates/fetchling-formats",
    "crates/fetchling-engine",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xychelsea/fetchling"
homepage = "https://github.com/xychelsea/fetchling"
rust-version = "1.75"

[workspace.dependencies]
fetchling-core = { path = "crates/fetchling-core", version = "0.1.0" }
fetchling-cli = { path = "crates/fetchling-cli", version = "0.1.0" }
fetchling-net = { path = "crates/fetchling-net", version = "0.1.0" }
fetchling-http = { path = "crates/fetchling-http", version = "0.1.0" }
fetchling-ftp = { path = "crates/fetchling-ftp", version = "0.1.0" }
fetchling-formats = { path = "crates/fetchling-formats", version = "0.1.0" }
fetchling-engine = { path = "crates/fetchling-engine", version = "0.1.0" }
thiserror = "2"
url = "2"
http = "1"
bytes = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "io-std", "fs", "time", "sync"] }
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
tokio-rustls = "0.26"
webpki-roots = "0.26"
regex = "1"
percent-encoding = "2"
encoding_rs = "0.8"
flate2 = "1"
base64 = "0.22"
sha1 = "0.10"
sha2 = "0.10"
md-5 = "0.10"
hex = "0.4"
hickory-resolver = { version = "0.26.1", default-features = false, features = ["tokio", "system-config"] }
cookie_store = "0.22"
quick-xml = "0.41"
httpdate = "1"
xattr = "1"
