/// Full fetchling configuration.
///
/// Field defaults follow wgetrc semantics unless noted.
#[derive(Debug, Clone)]
pub struct Config {
    pub background: bool,
    pub logfile: Option<String>,
    pub append_output: bool,
    pub debug: bool,
    pub quiet: bool,
    pub verbose: bool,
    pub report_speed_bits: bool,
    pub input_file: Option<String>,
    pub input_metalink: Option<String>,
    pub force_html: bool,
    pub force_css: bool,
    pub force_metalink: bool,
    pub force_rss: bool,
    pub force_atom: bool,
    pub force_sitemap: bool,
    pub follow_sitemaps: bool,
    pub base: Option<String>,
    pub config_file: Option<String>,
    pub no_config: bool,
    pub rejected_log: Option<String>,
    pub execute_commands: Vec<String>,

    pub bind_address: Option<String>,
    pub bind_dns_address: Option<String>,
    pub dns_servers: Option<String>,
    pub tries: u32,
    pub output_document: Option<String>,
    pub no_clobber: bool,
    /// Fetchling extension: auto-rename to `file.1`, `file.2`, … on collision.
    /// When false (default), overwrite on collision.
    pub unique_names: bool,
    pub backups: u32,
    pub continue_download: bool,
    pub start_pos: Option<u64>,
    pub progress: String,
    pub show_progress: bool,
    pub timestamping: bool,
    pub if_modified_since: bool,
    pub use_server_timestamps: bool,
    pub server_response: bool,
    pub spider: bool,
    pub timeout: Option<f64>,
    pub dns_timeout: Option<f64>,
    pub connect_timeout: Option<f64>,
    pub read_timeout: Option<f64>,
    pub limit_rate: Option<u64>,
    pub wait: f64,
    pub waitretry: f64,
    pub random_wait: bool,
    pub use_proxy: bool,
    pub http_proxy: Option<String>,
    pub https_proxy: Option<String>,
    pub quota: Option<u64>,
    pub dns_cache: bool,
    pub restrict_file_names: Vec<String>,
    pub inet4_only: bool,
    pub inet6_only: bool,
    pub prefer_family: String,
    pub retry_connrefused: bool,
    pub user: Option<String>,
    pub password: Option<String>,
    pub ask_password: bool,
    pub use_askpass: Option<String>,
    pub iri: bool,
    pub local_encoding: Option<String>,
    pub remote_encoding: Option<String>,
    pub unlink: bool,
    pub xattr: bool,
    pub keep_badhash: bool,
    pub metalink_over_http: bool,
    pub metalink_index: i32,
    pub preferred_location: Option<String>,
    /// Maximum concurrent downloads (`--max-threads`). Default 1 = serial.
    pub max_threads: u32,
    pub max_threads_per_host: u32,

    pub directories: bool,
    pub force_directories: bool,
    pub host_directories: bool,
    pub protocol_directories: bool,
    pub cut_dirs: u32,
    pub directory_prefix: String,

    pub default_page: String,
    pub adjust_extension: bool,
    pub http_user: Option<String>,
    pub http_password: Option<String>,
    pub http_keep_alive: bool,
    pub cache: bool,
    pub cookies: bool,
    pub load_cookies: Option<String>,
    pub save_cookies: Option<String>,
    pub keep_session_cookies: bool,
    pub ignore_length: bool,
    pub headers: Vec<String>,
    pub compression: String,
    pub max_redirect: u32,
    pub proxy_user: Option<String>,
    pub proxy_password: Option<String>,
    pub referer: Option<String>,
    pub save_headers: bool,
    pub user_agent: String,
    pub post_data: Option<String>,
    pub post_file: Option<String>,
    pub method: Option<String>,
    pub body_data: Option<String>,
    pub body_file: Option<String>,
    pub content_disposition: bool,
    pub content_on_error: bool,
    pub trust_server_names: bool,
    pub auth_no_challenge: bool,
    pub retry_on_host_error: bool,
    pub retry_on_http_error: Vec<u16>,
    pub netrc: bool,
    pub netrc_file: Option<String>,

    pub secure_protocol: String,
    pub https_only: bool,
    pub check_certificate: bool,
    pub certificate: Option<String>,
    pub certificate_type: String,
    pub private_key: Option<String>,
    pub private_key_type: String,
    pub ca_certificate: Option<String>,
    pub ca_directory: Option<String>,
    pub crl_file: Option<String>,
    pub pinnedpubkey: Option<String>,
    pub random_file: Option<String>,
    pub egd_file: Option<String>,
    pub hsts: bool,
    pub hsts_file: Option<String>,

    pub warc_file: Option<String>,
    pub warc_header: Vec<String>,
    pub warc_max_size: Option<u64>,
    pub warc_cdx: bool,
    pub warc_dedup: Option<String>,
    pub warc_compression: bool,
    pub warc_digests: bool,
    pub warc_keep_log: bool,
    pub warc_tempdir: Option<String>,

    pub ftp_user: Option<String>,
    pub ftp_password: Option<String>,
    pub remove_listing: bool,
    pub ftp_glob: bool,
    pub passive_ftp: bool,
    pub preserve_permissions: bool,
    pub retr_symlinks: bool,
    pub ftps_implicit: bool,
    pub ftps_resume_ssl: bool,
    pub ftps_clear_data_connection: bool,
    pub ftps_fallback_to_ftp: bool,

    pub recursive: bool,
    pub level: i32,
    pub delete_after: bool,
    pub convert_links: bool,
    pub convert_file_only: bool,
    pub backup_converted: bool,
    pub mirror: bool,
    pub page_requisites: bool,
    pub strict_comments: bool,

    pub accept: Vec<String>,
    pub reject: Vec<String>,
    pub filter_mime_type: Vec<String>,
    pub cut_url_get_vars: Option<Vec<String>>,
    pub cut_file_get_vars: Option<Vec<String>>,
    pub accept_regex: Option<String>,
    pub reject_regex: Option<String>,
    pub regex_type: String,
    pub domains: Vec<String>,
    pub exclude_domains: Vec<String>,
    pub follow_ftp: bool,
    pub follow_tags: Vec<String>,
    pub ignore_tags: Vec<String>,
    pub ignore_case: bool,
    pub span_hosts: bool,
    pub relative_only: bool,
    pub include_directories: Vec<String>,
    pub exclude_directories: Vec<String>,
    pub no_parent: bool,

    pub urls: Vec<String>,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            background: false,
            logfile: None,
            append_output: false,
            debug: false,
            quiet: false,
            verbose: true,
            report_speed_bits: false,
            input_file: None,
            input_metalink: None,
            force_html: false,
            force_css: false,
            force_metalink: false,
            force_rss: false,
            force_atom: false,
            force_sitemap: false,
            follow_sitemaps: false,
            base: None,
            config_file: None,
            no_config: false,
            rejected_log: None,
            execute_commands: Vec::new(),

            bind_address: None,
            bind_dns_address: None,
            dns_servers: None,
            tries: 20,
            output_document: None,
            no_clobber: false,
            unique_names: false,
            backups: 0,
            continue_download: false,
            start_pos: None,
            progress: "bar".into(),
            show_progress: false,
            timestamping: false,
            if_modified_since: true,
            use_server_timestamps: true,
            server_response: false,
            spider: false,
            timeout: None,
            dns_timeout: None,
            connect_timeout: None,
            read_timeout: Some(900.0),
            limit_rate: None,
            wait: 0.0,
            waitretry: 10.0,
            random_wait: false,
            use_proxy: true,
            http_proxy: None,
            https_proxy: None,
            quota: None,
            dns_cache: true,
            restrict_file_names: vec!["unix".into()],
            inet4_only: false,
            inet6_only: false,
            prefer_family: "none".into(),
            retry_connrefused: false,
            user: None,
            password: None,
            ask_password: false,
            use_askpass: None,
            iri: true,
            local_encoding: None,
            remote_encoding: None,
            unlink: false,
            xattr: false,
            keep_badhash: false,
            metalink_over_http: false,
            metalink_index: 0,
            preferred_location: None,
            max_threads: 1,
            max_threads_per_host: 0,

            directories: true,
            force_directories: false,
            host_directories: true,
            protocol_directories: false,
            cut_dirs: 0,
            directory_prefix: ".".into(),

            default_page: "index.html".into(),
            adjust_extension: false,
            http_user: None,
            http_password: None,
            http_keep_alive: true,
            cache: true,
            cookies: true,
            load_cookies: None,
            save_cookies: None,
            keep_session_cookies: false,
            ignore_length: false,
            headers: Vec::new(),
            compression: "none".into(),
            max_redirect: 20,
            proxy_user: None,
            proxy_password: None,
            referer: None,
            save_headers: false,
            user_agent: format!("fetchling/{}", env!("CARGO_PKG_VERSION")),
            post_data: None,
            post_file: None,
            method: None,
            body_data: None,
            body_file: None,
            content_disposition: false,
            content_on_error: false,
            trust_server_names: false,
            auth_no_challenge: false,
            retry_on_host_error: false,
            retry_on_http_error: Vec::new(),
            netrc: true,
            netrc_file: None,

            secure_protocol: "auto".into(),
            https_only: false,
            check_certificate: true,
            certificate: None,
            certificate_type: "pem".into(),
            private_key: None,
            private_key_type: "pem".into(),
            ca_certificate: None,
            ca_directory: None,
            crl_file: None,
            pinnedpubkey: None,
            random_file: None,
            egd_file: None,
            hsts: true,
            hsts_file: None,

            warc_file: None,
            warc_header: Vec::new(),
            warc_max_size: None,
            warc_cdx: false,
            warc_dedup: None,
            warc_compression: true,
            warc_digests: true,
            warc_keep_log: true,
            warc_tempdir: None,

            ftp_user: None,
            ftp_password: None,
            remove_listing: true,
            ftp_glob: true,
            passive_ftp: true,
            preserve_permissions: false,
            retr_symlinks: false,
            ftps_implicit: false,
            ftps_resume_ssl: true,
            ftps_clear_data_connection: false,
            ftps_fallback_to_ftp: false,

            recursive: false,
            level: 5,
            delete_after: false,
            convert_links: false,
            convert_file_only: false,
            backup_converted: false,
            mirror: false,
            page_requisites: false,
            strict_comments: false,

            accept: Vec::new(),
            reject: Vec::new(),
            filter_mime_type: Vec::new(),
            cut_url_get_vars: None,
            cut_file_get_vars: None,
            accept_regex: None,
            reject_regex: None,
            regex_type: "posix".into(),
            domains: Vec::new(),
            exclude_domains: Vec::new(),
            follow_ftp: false,
            follow_tags: Vec::new(),
            ignore_tags: Vec::new(),
            ignore_case: false,
            span_hosts: false,
            relative_only: false,
            include_directories: Vec::new(),
            exclude_directories: Vec::new(),
            no_parent: false,

            urls: Vec::new(),
        }
    }
}

impl Config {
    pub fn apply_mirror(&mut self) {
        self.recursive = true;
        self.level = -1; // infinite
        self.timestamping = true;
        self.remove_listing = false;
    }

    pub fn apply_timeout(&mut self, seconds: f64) {
        self.timeout = Some(seconds);
        self.dns_timeout = Some(seconds);
        self.connect_timeout = Some(seconds);
        self.read_timeout = Some(seconds);
    }

    pub fn effective_max_threads_per_host(&self) -> u32 {
        if self.max_threads_per_host == 0 {
            self.max_threads.clamp(1, 4)
        } else {
            self.max_threads_per_host
        }
    }

    pub fn finalize_concurrency(&mut self) {
        if self.max_threads_per_host == 0 {
            self.max_threads_per_host = self.effective_max_threads_per_host();
        }
    }
}
